export const siteUrl = 'https://sufyan-frontend.vercel.app';

export const person = {
  name: 'Muhammad Sufyan',
  role: 'Frontend Developer',
  stack: 'React · Next.js',
  email: 'sufyantechsolutions@gmail.com',
  phone: '+923438640594',
  location: 'Lahore, Pakistan',
  github: 'https://github.com/sufyan-frontend',
  linkedin: 'https://www.linkedin.com/in/sufyan-frontend',
  bio: 'Frontend Developer with 1.5+ years of experience building responsive, scalable, and production-ready web applications using React and Next.js.',
  fullBio: 'Frontend Developer with 1.5+ years of experience building responsive, scalable, and production-ready web applications using React and Next.js. Experienced in developing real-world platforms for education, software companies, and business solutions. Strong focus on UI/UX, performance, and clean code practices. Currently working on multiple deployed production projects, including education portals, company websites, and SaaS-style platforms.',
  objective: 'Seeking a Frontend Developer role where I can contribute to scalable web applications, improve UI/UX systems, and grow into a mid/senior-level developer role in a professional engineering environment.',
};

export const skills = [
  { name: 'HTML5 & CSS3', level: 95, category: 'Core' },
  { name: 'JavaScript (ES6+)', level: 88, category: 'Core' },
  { name: 'React.js', level: 90, category: 'Framework' },
  { name: 'Next.js', level: 88, category: 'Framework' },
  { name: 'Tailwind CSS', level: 92, category: 'Styling' },
  { name: 'Bootstrap', level: 84, category: 'Styling' },
  { name: 'REST API Integration', level: 82, category: 'Integration' },
  { name: 'Git & GitHub', level: 86, category: 'Tools' },
  { name: 'Responsive Design', level: 94, category: 'Core' },
  { name: 'Redux / State Mgmt', level: 70, category: 'State' },
  { name: 'Vercel / Netlify', level: 88, category: 'Tools' },
  { name: 'TypeScript', level: 72, category: 'Core' },
];

export const projects = [
  {
    id: 'sufyan-frontend-dashboard',
    title: 'Sufyan Frontend Dashboard',
    description: 'A modern, fully responsive admin dashboard built with Next.js and Tailwind CSS featuring clean data visualizations, sidebar navigation, and a professional dark UI.',
    url: 'https://sufyan-frontend-dashboard.vercel.app/',
    image: '/porfolio%20image/sufyan-frontend-dashboard.png',
    tags: ['Next.js', 'Dashboard', 'Tailwind CSS', 'Admin UI'],
    featured: true,
  },
  {
    id: 'alif-laila',
    title: 'Alif Laila Education Platform',
    description: 'Full education management UI system with role-based dashboards and structured UI components built for a large-scale educational institution.',
    url: 'https://aliflaila.app/',
    image: '/porfolio%20image/aliflaila-app.png',
    tags: ['React', 'Next.js', 'Dashboard', 'Education'],
    featured: true,
  },
  {
    id: 'ehya',
    title: 'Ehya Education Platform',
    description: 'Complete institutional web platform with responsive UI and modern frontend architecture, serving thousands of students and faculty.',
    url: 'https://www.ehya.com.pk/',
    image: '/porfolio%20image/ehya-pk.png',
    tags: ['Next.js', 'Tailwind CSS', 'Education'],
    featured: true,
  },
  {
    id: 'classmate',
    title: 'Classmate Portal',
    description: 'Student and teacher interface system with clean dashboard-based UI design for managing classes, assignments, and academic data.',
    url: 'https://classmate.ehya.com.pk/',
    image: '/porfolio%20image/classmate-ehya-pk.png',
    tags: ['React', 'Dashboard', 'Education', 'UI/UX'],
    featured: true,
  },
  {
    id: 'tillshop',
    title: 'TillShop Technologies',
    description: 'Corporate software house website with modern landing page design, service showcases, and professional company branding.',
    url: 'https://www.tillshoptechnologies.com/',
    image: '/porfolio%20image/tillshoptechnologies.png',
    tags: ['Next.js', 'Corporate', 'Landing Page'],
    featured: false,
  },
  {
    id: 'fieldxai',
    title: 'FieldX AI',
    description: 'AI-powered platform with a modern, responsive frontend delivering a clean and professional user experience for field operations and intelligent workflows.',
    url: 'https://fieldxai.com/',
    image: '/porfolio%20image/fieldxai.png',
    tags: ['Next.js', 'AI', 'SaaS', 'Tailwind CSS'],
    featured: false,
  },
  {
    id: 'ehsas',
    title: 'Ehsas Next App',
    description: 'React-based web application deployed on Vercel with optimized UI architecture and component-based design system.',
    url: 'https://ehsasnext.vercel.app/',
    image: '/porfolio%20image/ehsasnext-vercel-app.png',
    tags: ['React', 'Vercel', 'App'],
    featured: false,
  },
  {
    id: 'anp',
    title: 'ANP Engineering Website',
    description: 'Professional business website for an engineering company with responsive design, service listings, and corporate branding.',
    url: 'https://www.anpengineerings.com/',
    image: '/porfolio%20image/anpengineerings.png',
    tags: ['Next.js', 'Corporate', 'Responsive'],
    featured: false,
  },
  {
    id: 'faizan-noor-ul-quran',
    title: 'Faizan Noor ul Quran',
    description: 'Islamic education platform for Quran learning with a clean, user-friendly interface designed to serve students and teachers effectively.',
    url: 'http://faizan-noor-ul-quran-s.vercel.app/',
    image: '/porfolio%20image/faizan-noor-ul-quran.png',
    tags: ['Next.js', 'Education', 'Islamic'],
    featured: false,
  },
  {
    id: 'soft-ehya',
    title: 'Soft Ehya',
    description: 'Software division platform for Ehya Education, showcasing tech services and digital solutions with a professional corporate design.',
    url: 'http://soft.ehya.com.pk/',
    image: '/porfolio%20image/soft-ehya.png',
    tags: ['Next.js', 'Corporate', 'Software'],
    featured: false,
  },
  {
    id: 'tillshop-new',
    title: 'TillShop New',
    description: 'Redesigned and modernised version of the TillShop Technologies website with an updated layout, refreshed branding, and improved UI.',
    url: 'https://tillshopnew.vercel.app/',
    image: '/porfolio%20image/tillshopnew.png',
    tags: ['Next.js', 'Corporate', 'Redesign'],
    featured: false,
  },
];

export const experience = [
  {
    role: 'Frontend Developer (Intern → Junior)',
    company: 'Ehya Education',
    url: 'https://www.ehya.com.pk/',
    location: 'Lahore, Pakistan',
    duration: '1.5+ Years',
    period: '2025 – Present',
    highlights: [
      'Developed and maintained multiple education-based web platforms',
      'Converted UI designs into responsive React/Next.js applications',
      'Integrated REST APIs and handled dynamic data rendering',
      'Worked on production systems actively used by thousands of users',
      'Fixed UI/UX issues and improved performance metrics across pages',
      'Collaborated effectively with backend and design teams',
    ],
  },
  {
    role: 'Learner → Instructor & Freelancer',
    company: 'Ehsas Lab',
    url: 'https://ehsaslab.com/',
    location: 'Lahore, Pakistan',
    duration: '1+ Year',
    period: '2024 – 2025',
    highlights: [
      'Completed a 6-month intensive web development programme — HTML, CSS, JavaScript, and React',
      'Progressed from student to Instructor, teaching frontend development to new learners',
      'Awarded Best Instructor Certificate by Ehsas Lab for outstanding teaching contributions',
      'Took on freelance client projects, building real-world web solutions independently',
      'Self-learned Next.js, Tailwind CSS, Redux, Zod, Git, GitLab, Vercel, Netlify, and React Native',
    ],
  },
];

export const services = [
  {
    title: 'Frontend Development',
    description: 'Building fast, scalable, production-ready web applications using React and Next.js with clean, maintainable code.',
    icon: 'code',
  },
  {
    title: 'Responsive Web Design',
    description: 'Mobile-first, pixel-perfect designs that look flawless on any screen size, from phones to large desktops.',
    icon: 'mobile',
  },
  {
    title: 'API Integration',
    description: 'Connecting frontends to RESTful APIs and backend services with proper error handling and state management.',
    icon: 'api',
  },
  {
    title: 'UI/UX Implementation',
    description: 'Converting Figma or design mockups into clean, accessible, and beautifully interactive user interfaces.',
    icon: 'design',
  },
  {
    title: 'Performance Optimization',
    description: 'Improving Core Web Vitals, load times, and overall app performance for better SEO and user experience.',
    icon: 'speed',
  },
  {
    title: 'Deployment & Hosting',
    description: 'Deploying and managing projects on Vercel and Netlify with CI/CD pipelines and domain configuration.',
    icon: 'cloud',
  },
];

export const testimonials = [
  {
    name: 'Ali Hassan',
    role: 'Project Manager',
    company: 'Ehya Education',
    text: 'Sufyan consistently delivered high-quality UI work on time. His attention to detail and deep understanding of responsive design made a real difference in our products.',
  },
  {
    name: 'Usman Malik',
    role: 'Backend Developer',
    company: 'Ehya Education',
    text: 'Working with Sufyan has been seamless. He integrates APIs cleanly, asks the right questions, and communicates effectively about frontend requirements.',
  },
  {
    name: 'Sara Ahmed',
    role: 'UI/UX Designer',
    company: 'Freelance',
    text: 'Sufyan translates designs into code with impressive accuracy. His attention to spacing, color, and interactivity brings mockups to life exactly as intended.',
  },
];

export const practiceProjects = [
  {
    id: 'chatbot-ui',
    title: 'Chat Bot UI',
    description: 'A clean and interactive chatbot user interface built as a practice project to sharpen React component design, state management, and real-time UI patterns.',
    url: 'https://chat-botui.netlify.app/',
    image: '/practicewebsite/chabot.png',
    tags: ['React', 'CSS', 'UI Design', 'Practice'],
  },
  {
    id: 'hiba-logic',
    title: 'Hiba Logic',
    description: 'A practice frontend project showcasing modern UI layout, component structuring, and responsive design techniques built and deployed on Netlify.',
    url: 'https://sufyan-frontend-hibalogic.netlify.app/',
    image: '/practicewebsite/hibalogic.png',
    tags: ['React', 'Netlify', 'Responsive', 'Practice'],
  },
  {
    id: 'ehsas-lab-new',
    title: 'Ehsas Lab (Redesign)',
    description: 'A redesigned practice version of the Ehsas Lab website with improved UI layout, modern styling, and enhanced responsiveness deployed on Netlify.',
    url: 'https://ehsas-lab.netlify.app/',
    image: '/practicewebsite/ehsaslabnew.png',
    tags: ['React', 'Netlify', 'Redesign', 'Practice'],
  },
  {
    id: 'music-app',
    title: 'Music App UI',
    description: 'A practice music application UI with a stylish and modern interface, built to explore creative layouts, animations, and component design in React.',
    url: 'https://suf13.netlify.app/',
    image: '/practicewebsite/music.png',
    tags: ['React', 'Netlify', 'UI Design', 'Practice'],
  },
  {
    id: 'uniq-form',
    title: 'Uniq Form',
    description: 'A practice project focused on building clean, accessible, and well-designed form UI components with validation and smooth user interaction.',
    url: 'https://s-f.netlify.app/',
    image: '/practicewebsite/uniqform.png',
    tags: ['React', 'Netlify', 'Forms', 'Practice'],
  },
];

export const blogPosts = [
  // ── CATEGORY A: Personal Brand ──
  {
    slug: 'who-is-muhammad-sufyan',
    title: 'Who Is Muhammad Sufyan? Meet the Frontend Developer Behind Sufyan Frontend',
    excerpt: 'Muhammad Sufyan is a frontend developer from Lahore, Pakistan specialising in React.js and Next.js — building production-ready web apps for education platforms, SaaS products, and corporate clients.',
    date: '2026-06-01',
    readTime: '5 min',
    tags: ['Muhammad Sufyan', 'Frontend Developer', 'Lahore Pakistan'],
  },
  {
    slug: 'sufyan-frontend-developer-portfolio-2026',
    title: 'Sufyan Frontend Developer Portfolio 2026: React & Next.js Projects',
    excerpt: 'Explore the 2026 developer portfolio of Sufyan Frontend — a Lahore-based React and Next.js specialist with live production projects across education, AI, and corporate sectors.',
    date: '2026-05-20',
    readTime: '6 min',
    tags: ['Portfolio', 'Muhammad Sufyan', 'Next.js'],
  },
  {
    slug: 'muhammad-sufyan-github-projects',
    title: 'Muhammad Sufyan GitHub Projects: Open Source React & Next.js Work',
    excerpt: 'A deep dive into the GitHub profile of Muhammad Sufyan, showcasing his open-source repositories, frontend architecture patterns, and real-world React and Next.js projects.',
    date: '2026-04-15',
    readTime: '5 min',
    tags: ['GitHub', 'Muhammad Sufyan', 'Open Source'],
  },
  {
    slug: 'hire-sufyan-frontend-developer',
    title: 'Hire Sufyan Frontend Developer — React & Next.js Expert from Pakistan',
    excerpt: 'Looking to hire a skilled React and Next.js frontend developer from Pakistan? Muhammad Sufyan delivers responsive, scalable, and SEO-optimized web applications for startups and enterprises.',
    date: '2026-03-10',
    readTime: '4 min',
    tags: ['Hire Frontend Developer', 'Muhammad Sufyan', 'React Next.js'],
  },
  {
    slug: 'sufyan-frontend-developer-lahore-pakistan',
    title: 'Sufyan Frontend Developer Lahore Pakistan — React & Next.js Specialist',
    excerpt: 'Muhammad Sufyan is a top frontend developer from Lahore, Pakistan, known for building high-performance React and Next.js applications for clients across education, AI, and business sectors.',
    date: '2026-02-14',
    readTime: '5 min',
    tags: ['Lahore Pakistan', 'Frontend Developer', 'Muhammad Sufyan'],
  },
  {
    slug: 'muhammad-sufyan-linkedin-profile',
    title: 'Muhammad Sufyan LinkedIn Profile — Frontend Developer Career Story',
    excerpt: 'Discover the professional journey of Muhammad Sufyan on LinkedIn — from learning web development at Ehsas Lab to building production platforms at Ehya Education in Lahore, Pakistan.',
    date: '2026-01-08',
    readTime: '4 min',
    tags: ['LinkedIn', 'Muhammad Sufyan', 'Career'],
  },
  // ── CATEGORY B: Project-specific ──
  {
    slug: 'alif-laila-education-platform-nextjs',
    title: 'Alif Laila Education Platform: Built with Next.js by Muhammad Sufyan',
    excerpt: 'A case study of the Alif Laila Education Platform at aliflaila.app — a large-scale education management system built with React and Next.js featuring role-based dashboards and modern UI.',
    date: '2025-12-20',
    readTime: '7 min',
    tags: ['Next.js', 'Education Platform', 'Case Study'],
  },
  {
    slug: 'ehya-education-platform-development',
    title: 'Ehya Education Platform: Full Institutional Website Built with Next.js',
    excerpt: 'How Muhammad Sufyan developed the Ehya Education Platform at ehya.com.pk — a production-grade institutional web platform built with Next.js and Tailwind CSS serving thousands of students.',
    date: '2025-11-28',
    readTime: '7 min',
    tags: ['Next.js', 'Ehya Education', 'Case Study'],
  },
  {
    slug: 'classmate-portal-react-dashboard',
    title: 'Classmate Portal: A React-Powered Student Dashboard by Muhammad Sufyan',
    excerpt: 'Behind the scenes of the Classmate Portal at classmate.ehya.com.pk — a React-based student and teacher dashboard system built by Sufyan Frontend for seamless academic data management.',
    date: '2025-11-05',
    readTime: '6 min',
    tags: ['React', 'Dashboard', 'Education'],
  },
  {
    slug: 'tillshop-technologies-website',
    title: 'TillShop Technologies Website: Corporate Landing Page Development',
    excerpt: 'An inside look at how Muhammad Sufyan designed and built the TillShop Technologies website at tillshoptechnologies.com — a modern corporate landing page with professional branding.',
    date: '2025-10-18',
    readTime: '5 min',
    tags: ['Next.js', 'Corporate Website', 'Landing Page'],
  },
  {
    slug: 'fieldxai-ai-platform-nextjs',
    title: 'FieldX AI Platform: Building an AI SaaS Frontend with Next.js',
    excerpt: 'A technical look at the FieldX AI platform at fieldxai.com — how Muhammad Sufyan built a modern, responsive frontend for an AI-powered field operations product using Next.js and Tailwind CSS.',
    date: '2025-10-01',
    readTime: '7 min',
    tags: ['Next.js', 'AI Platform', 'SaaS'],
  },
  {
    slug: 'sufyan-frontend-dashboard-project',
    title: 'Sufyan Frontend Dashboard: Admin UI Built with Next.js & Tailwind CSS',
    excerpt: 'Explore the Sufyan Frontend Dashboard at sufyan-frontend-dashboard.vercel.app — a fully responsive admin dashboard built by Muhammad Sufyan with dark UI, data visualisations, and sidebar navigation.',
    date: '2025-09-20',
    readTime: '6 min',
    tags: ['Dashboard', 'Next.js', 'Tailwind CSS'],
  },
  {
    slug: 'faizan-noor-ul-quran-platform',
    title: 'Faizan Noor ul Quran: Islamic Education Platform Built with Next.js',
    excerpt: 'How Muhammad Sufyan built the Faizan Noor ul Quran Islamic education platform — a clean, user-friendly Quran learning site with an intuitive interface for students and teachers.',
    date: '2025-09-10',
    readTime: '5 min',
    tags: ['Next.js', 'Islamic Education', 'Web App'],
  },
  {
    slug: 'anp-engineering-corporate-website',
    title: 'ANP Engineering Corporate Website: Responsive Business Site by Sufyan',
    excerpt: 'A walkthrough of the ANP Engineering website at anpengineerings.com — a professional corporate site built by Muhammad Sufyan with responsive design, service listings, and modern branding.',
    date: '2025-09-05',
    readTime: '5 min',
    tags: ['Corporate Website', 'Next.js', 'Responsive Design'],
  },
  {
    slug: 'ehsas-next-app-react',
    title: 'Ehsas Next App: React Web Application Deployed on Vercel',
    excerpt: 'A look at the Ehsas Next App — a React-based web application developed by Muhammad Sufyan and deployed on Vercel with an optimised UI architecture and component-driven design system.',
    date: '2025-09-01',
    readTime: '5 min',
    tags: ['React', 'Vercel', 'Web App'],
  },
  // ── CATEGORY C: Technical React/Next.js ──
  {
    slug: 'nextjs-15-turbopack-guide',
    title: 'Next.js 15 Turbopack Guide: Faster Builds and Hot Reload in 2026',
    excerpt: 'Everything you need to know about Turbopack in Next.js 15 — how it replaces Webpack, delivers lightning-fast HMR, and changes local development workflows for React developers.',
    date: '2026-05-05',
    readTime: '8 min',
    tags: ['Next.js 15', 'Turbopack', 'Performance'],
  },
  {
    slug: 'react-19-new-features',
    title: 'React 19 New Features Every Developer Should Know in 2026',
    excerpt: 'React 19 ships transformative changes — Actions, useActionState, the React Compiler, improved Suspense, and native form handling. Here is what every React developer needs to understand.',
    date: '2026-04-25',
    readTime: '9 min',
    tags: ['React 19', 'JavaScript', 'Frontend'],
  },
  {
    slug: 'nextjs-server-components-guide',
    title: 'Next.js Server Components Guide: When and How to Use Them',
    excerpt: 'A practical guide to Next.js Server Components — understanding the server/client boundary, data fetching patterns, and how to structure your Next.js app for maximum performance.',
    date: '2026-04-10',
    readTime: '8 min',
    tags: ['Next.js', 'Server Components', 'React'],
  },
  {
    slug: 'tailwind-css-v4-features',
    title: 'Tailwind CSS v4 New Features: What Changed and How to Migrate',
    excerpt: 'Tailwind CSS v4 brings a new CSS-first configuration system, a faster engine, and major API changes. This guide walks through every key change and how to upgrade your projects.',
    date: '2026-03-28',
    readTime: '7 min',
    tags: ['Tailwind CSS v4', 'CSS', 'Migration'],
  },
  {
    slug: 'react-hooks-complete-guide',
    title: 'React Hooks Complete Guide 2026: From useState to useOptimistic',
    excerpt: 'A comprehensive guide to all React hooks in 2026 — covering core hooks, new React 19 hooks like useActionState and useOptimistic, and patterns for building clean, reusable React logic.',
    date: '2026-03-15',
    readTime: '10 min',
    tags: ['React Hooks', 'React 19', 'JavaScript'],
  },
  {
    slug: 'nextjs-image-optimization',
    title: 'Next.js Image Optimization: Complete Guide to the next/image Component',
    excerpt: 'Master the Next.js Image component — lazy loading, responsive sizes, priority hints, blur placeholders, and how image optimisation directly boosts your Core Web Vitals and SEO.',
    date: '2026-03-01',
    readTime: '7 min',
    tags: ['Next.js', 'Image Optimization', 'Performance'],
  },
  {
    slug: 'typescript-react-guide',
    title: 'TypeScript with React: A Practical Guide for 2026 Projects',
    excerpt: 'Learn how to effectively use TypeScript in React and Next.js projects — from typing props and hooks to generics, discriminated unions, and best practices for scalable frontend codebases.',
    date: '2026-02-20',
    readTime: '9 min',
    tags: ['TypeScript', 'React', 'JavaScript'],
  },
  {
    slug: 'nextjs-seo-guide-2026',
    title: 'Next.js SEO Guide 2026: Metadata API, Sitemaps, and Structured Data',
    excerpt: 'A complete Next.js SEO guide for 2026 — using the Metadata API, generating sitemaps, adding structured data, optimizing Open Graph tags, and achieving top search rankings.',
    date: '2026-02-08',
    readTime: '8 min',
    tags: ['Next.js', 'SEO', 'Metadata API'],
  },
  {
    slug: 'react-performance-2026',
    title: 'React Performance Optimization in 2026: Compiler, Memo, and Beyond',
    excerpt: 'Advanced React performance techniques for 2026 — the React Compiler, smart memoisation, virtualization, code splitting, bundle analysis, and real-world optimisation strategies.',
    date: '2026-01-25',
    readTime: '9 min',
    tags: ['React', 'Performance', 'Optimization'],
  },
  {
    slug: 'nextjs-api-routes',
    title: 'Next.js API Routes and Route Handlers: A 2026 Practical Guide',
    excerpt: 'Everything about Next.js API routes and the new Route Handlers — GET, POST, middleware integration, error handling, and building full-stack features directly inside your Next.js app.',
    date: '2026-01-15',
    readTime: '7 min',
    tags: ['Next.js', 'API Routes', 'Full Stack'],
  },
  {
    slug: 'tailwind-dark-mode-guide',
    title: 'Tailwind CSS Dark Mode Guide: CSS Variables and Theme Switching',
    excerpt: 'Implement seamless dark mode in React and Next.js apps with Tailwind CSS — using CSS variables, the class strategy, next-themes integration, and system preference detection.',
    date: '2025-12-30',
    readTime: '6 min',
    tags: ['Tailwind CSS', 'Dark Mode', 'React'],
  },
  {
    slug: 'react-state-management-2026',
    title: 'React State Management in 2026: Zustand, Context, and Server State',
    excerpt: 'A modern guide to React state management — comparing useState, Context API, Zustand, TanStack Query, and when to use each for scalable Next.js and React applications.',
    date: '2025-12-10',
    readTime: '8 min',
    tags: ['React', 'State Management', 'Zustand'],
  },
  {
    slug: 'nextjs-vercel-deployment',
    title: 'Deploy Next.js to Vercel: Complete Step-by-Step Guide for 2026',
    excerpt: 'The definitive guide to deploying Next.js applications on Vercel — from initial setup to custom domains, environment variables, preview deployments, and CI/CD configuration.',
    date: '2025-11-22',
    readTime: '6 min',
    tags: ['Next.js', 'Vercel', 'Deployment'],
  },
  {
    slug: 'responsive-design-tailwind',
    title: 'Responsive Design with Tailwind CSS: Mobile-First Patterns in 2026',
    excerpt: 'Build perfectly responsive web layouts using Tailwind CSS — mobile-first breakpoints, responsive grids, container queries, and real-world layout patterns for modern React apps.',
    date: '2025-11-10',
    readTime: '7 min',
    tags: ['Tailwind CSS', 'Responsive Design', 'CSS'],
  },
  {
    slug: 'react-forms-useactionstate',
    title: 'React Forms with useActionState: Server Actions and Form Handling in 2026',
    excerpt: 'Master modern React form handling with useActionState and Server Actions in Next.js — replacing complex form libraries with native React 19 patterns for clean, performant forms.',
    date: '2025-10-28',
    readTime: '7 min',
    tags: ['React 19', 'Forms', 'Server Actions'],
  },
  {
    slug: 'nextjs-metadata-api',
    title: 'Next.js Metadata API: Dynamic SEO Tags, OG Images, and Canonical URLs',
    excerpt: 'Learn to use the Next.js Metadata API to generate dynamic page titles, descriptions, Open Graph images, Twitter cards, canonical URLs, and structured data for better SEO.',
    date: '2025-10-12',
    readTime: '7 min',
    tags: ['Next.js', 'Metadata API', 'SEO'],
  },
  {
    slug: 'framer-motion-react',
    title: 'Framer Motion with React: Animations, Transitions, and Scroll Effects',
    excerpt: 'A hands-on guide to adding professional animations to React and Next.js apps with Framer Motion — variants, scroll-triggered animations, layout transitions, and performance tips.',
    date: '2025-09-28',
    readTime: '8 min',
    tags: ['Framer Motion', 'React', 'Animations'],
  },
  {
    slug: 'nextjs-loading-suspense',
    title: 'Next.js Loading UI and Suspense: Streaming and Skeleton Screens',
    excerpt: 'How to implement loading states and streaming in Next.js using the loading.tsx convention, React Suspense boundaries, and skeleton screens for a smooth user experience.',
    date: '2025-09-18',
    readTime: '6 min',
    tags: ['Next.js', 'Suspense', 'UX'],
  },
  {
    slug: 'react-19-useactionstate',
    title: 'React 19 useActionState Hook: Complete Guide with Examples',
    excerpt: 'A deep dive into React 19\'s useActionState hook — how it works with Server Actions, replaces useFormState, handles pending states, and simplifies async mutations in Next.js.',
    date: '2025-09-12',
    readTime: '7 min',
    tags: ['React 19', 'useActionState', 'Hooks'],
  },
  {
    slug: 'nextjs-middleware-guide',
    title: 'Next.js Middleware Guide: Authentication, Redirects, and Edge Functions',
    excerpt: 'Master Next.js middleware — protecting routes, handling authentication redirects, A/B testing, geolocation logic, and writing efficient edge functions for your Next.js app.',
    date: '2025-09-08',
    readTime: '7 min',
    tags: ['Next.js', 'Middleware', 'Authentication'],
  },
  // ── CATEGORY D: Career/Pakistan ──
  {
    slug: 'frontend-developer-lahore-pakistan',
    title: 'Frontend Developer in Lahore, Pakistan: Career Guide and Opportunities',
    excerpt: 'A comprehensive guide to becoming a frontend developer in Lahore, Pakistan — local job market insights, top companies hiring, required skills, and how developers like Muhammad Sufyan built their careers.',
    date: '2026-05-15',
    readTime: '7 min',
    tags: ['Lahore Pakistan', 'Frontend Developer', 'Career'],
  },
  {
    slug: 'react-developer-jobs-pakistan-2026',
    title: 'React Developer Jobs in Pakistan 2026: Where to Find Them and How to Apply',
    excerpt: 'The complete guide to finding React developer jobs in Pakistan in 2026 — top companies, job portals, salary expectations, and how to stand out with a strong portfolio like Sufyan Frontend.',
    date: '2026-04-20',
    readTime: '8 min',
    tags: ['React Jobs', 'Pakistan', '2026'],
  },
  {
    slug: 'freelance-frontend-developer-pakistan',
    title: 'Freelance Frontend Developer in Pakistan: How to Get Clients in 2026',
    excerpt: 'A practical guide to freelancing as a frontend developer in Pakistan — building a client pipeline, pricing your services, using Upwork and Fiverr, and growing like Muhammad Sufyan did.',
    date: '2026-03-22',
    readTime: '7 min',
    tags: ['Freelance', 'Pakistan', 'Frontend Developer'],
  },
  {
    slug: 'frontend-developer-salary-pakistan-2026',
    title: 'Frontend Developer Salary in Pakistan 2026: Realistic Numbers Explained',
    excerpt: 'An honest breakdown of frontend developer salaries in Pakistan in 2026 — entry-level to senior, Lahore vs remote, React/Next.js specialist pay, and how to negotiate your worth.',
    date: '2026-02-28',
    readTime: '6 min',
    tags: ['Salary', 'Pakistan', 'Frontend Developer'],
  },
  {
    slug: 'become-frontend-developer-pakistan',
    title: 'How to Become a Frontend Developer in Pakistan: Step-by-Step Roadmap',
    excerpt: 'The complete roadmap to becoming a frontend developer in Pakistan in 2026 — from HTML basics to React, Next.js, and landing your first job, inspired by Muhammad Sufyan\'s own learning path.',
    date: '2026-02-01',
    readTime: '9 min',
    tags: ['Roadmap', 'Pakistan', 'Learn Frontend'],
  },
  {
    slug: 'react-nextjs-portfolio-guide',
    title: 'Build a React & Next.js Developer Portfolio That Gets You Hired in 2026',
    excerpt: 'How to build a standout frontend developer portfolio using React and Next.js — project selection, design principles, SEO, and lessons from building sufyan-frontend.vercel.app.',
    date: '2026-01-20',
    readTime: '8 min',
    tags: ['Portfolio', 'React', 'Next.js'],
  },
  {
    slug: 'github-profile-frontend-developer',
    title: 'GitHub Profile Optimization for Frontend Developers: Complete 2026 Guide',
    excerpt: 'How to build a GitHub profile that impresses recruiters and clients — READMEs, pinned repositories, contribution graphs, and lessons from Muhammad Sufyan\'s GitHub at github.com/sufyan-frontend.',
    date: '2025-12-25',
    readTime: '6 min',
    tags: ['GitHub', 'Frontend Developer', 'Career'],
  },
  {
    slug: 'linkedin-frontend-developer-pakistan',
    title: 'LinkedIn for Frontend Developers in Pakistan: Profile Tips That Get Noticed',
    excerpt: 'How Pakistani frontend developers can build a LinkedIn profile that attracts recruiters, clients, and opportunities — using Muhammad Sufyan\'s linkedin.com/in/sufyan-frontend as a reference.',
    date: '2025-12-05',
    readTime: '6 min',
    tags: ['LinkedIn', 'Pakistan', 'Frontend Developer'],
  },
  {
    slug: 'web-development-career-pakistan',
    title: 'Web Development Career in Pakistan 2026: Opportunities, Salaries, and Growth',
    excerpt: 'A thorough guide to web development careers in Pakistan in 2026 — the booming tech industry in Lahore and Karachi, key skills employers want, and how developers like Muhammad Sufyan are leading the way.',
    date: '2025-11-15',
    readTime: '8 min',
    tags: ['Web Development', 'Pakistan', 'Career'],
  },
  {
    slug: 'frontend-developer-skills-2026',
    title: 'Frontend Developer Skills in 2026: What Employers Actually Want',
    excerpt: 'The must-have frontend developer skills for 2026 — React 19, Next.js 15, TypeScript, Tailwind CSS, testing, accessibility, and the soft skills that separate good developers from great ones.',
    date: '2025-10-25',
    readTime: '7 min',
    tags: ['Skills', 'Frontend Developer', '2026'],
  },
  // ── CATEGORY E: General Web Dev ──
  {
    slug: 'core-web-vitals-nextjs',
    title: 'Core Web Vitals in Next.js: Optimizing LCP, CLS, and INP in 2026',
    excerpt: 'How to measure and improve Core Web Vitals in your Next.js apps — optimizing LCP with image priority, eliminating CLS from dynamic content, and reducing INP for a perfect Google score.',
    date: '2025-12-15',
    readTime: '8 min',
    tags: ['Core Web Vitals', 'Next.js', 'SEO'],
  },
  {
    slug: 'seo-nextjs-websites-2026',
    title: 'SEO for Next.js Websites in 2026: The Complete Technical Guide',
    excerpt: 'A technical SEO guide built specifically for Next.js websites — Metadata API, structured data, sitemaps, robots.txt, canonical tags, and performance strategies for top search rankings.',
    date: '2025-11-30',
    readTime: '9 min',
    tags: ['SEO', 'Next.js', 'Technical SEO'],
  },
  {
    slug: 'javascript-es6-features',
    title: 'JavaScript ES6+ Features Every React Developer Must Know in 2026',
    excerpt: 'A practical guide to modern JavaScript features essential for React development — destructuring, spread/rest, optional chaining, nullish coalescing, async/await, modules, and ES2025 additions.',
    date: '2025-11-01',
    readTime: '8 min',
    tags: ['JavaScript', 'ES6+', 'React'],
  },
  {
    slug: 'git-github-best-practices',
    title: 'Git and GitHub Best Practices for Frontend Developers in 2026',
    excerpt: 'Master Git and GitHub as a frontend developer — branching strategies, commit message conventions, pull request workflows, code review practices, and collaboration tips for React and Next.js projects.',
    date: '2025-10-08',
    readTime: '7 min',
    tags: ['Git', 'GitHub', 'Best Practices'],
  },
  {
    slug: 'web-accessibility-react',
    title: 'Web Accessibility in React: Building Inclusive Apps in 2026',
    excerpt: 'How to build accessible React and Next.js applications — semantic HTML, ARIA roles, keyboard navigation, focus management, colour contrast, and tools to audit your app for WCAG compliance.',
    date: '2025-09-22',
    readTime: '8 min',
    tags: ['Accessibility', 'React', 'WCAG'],
  },
  // ── Original posts (preserved) ──
  {
    slug: 'nextjs-app-router-guide',
    title: 'Getting Started with Next.js App Router',
    excerpt: 'A practical guide to building modern web apps with Next.js App Router, Server Components, and the latest features for improved performance and developer experience.',
    date: '2025-05-15',
    readTime: '6 min',
    tags: ['Next.js', 'React', 'Web Dev'],
  },
  {
    slug: 'tailwind-css-tips',
    title: 'Tailwind CSS Best Practices for React Projects',
    excerpt: 'Clean and maintainable Tailwind CSS patterns for large-scale React projects — from component variants to responsive layout strategies.',
    date: '2025-04-20',
    readTime: '5 min',
    tags: ['Tailwind CSS', 'React', 'CSS'],
  },
  {
    slug: 'react-performance',
    title: 'React Performance Optimization in 2025',
    excerpt: 'Practical, real-world techniques for optimizing React apps — useMemo, useCallback, lazy loading, Suspense, and the new React Compiler.',
    date: '2025-03-10',
    readTime: '8 min',
    tags: ['React', 'Performance', 'JavaScript'],
  },
];
