import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { blogPosts } from "@/lib/data";
import { blogContent } from "@/lib/blog-content";

const hasContent = (slug: string) => slug in blogContent;

export function generateStaticParams() {
  // `seo-fundamentals` has its own dedicated route (blog/seo-fundamentals/page.tsx),
  // so exclude it here to avoid a static/dynamic path collision at build time.
  return blogPosts.filter((post) => post.slug !== "seo-fundamentals").map((post) => ({ slug: post.slug }));
}

type Props = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const post = blogPosts.find((p) => p.slug === slug);
  if (!post) return {};
  return {
    title: post.title,
    description: post.excerpt,
    keywords: [
      ...post.tags,
      "Muhammad Sufyan", "sufyanjutt", "sufyanfrontend",
      "Frontend Developer Pakistan", "React Next.js tutorial",
    ],
    authors: [{ name: "Muhammad Sufyan", url: "https://sufyan-frontend.vercel.app" }],
    alternates: { canonical: `https://sufyan-frontend.vercel.app/blog/${post.slug}` },
    robots: hasContent(post.slug) ? undefined : { index: false, follow: false },
    openGraph: {
      type: "article",
      title: post.title,
      description: post.excerpt,
      url: `https://sufyan-frontend.vercel.app/blog/${post.slug}`,
      publishedTime: post.date,
      authors: ["Muhammad Sufyan"],
      tags: post.tags,
      // Per-post OG image is generated by blog/[slug]/opengraph-image.tsx.
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.excerpt,
      // Twitter falls back to the generated opengraph-image.
    },
  };
}

export default async function BlogPost({ params }: Props) {
  const { slug } = await params;
  const post = blogPosts.find((p) => p.slug === slug);
  if (!post) notFound();

  // Related posts: only link to indexable articles (same rule as generateMetadata's
  // noindex), ranked by shared tags then recency, so every article links out to 3
  // more — distributing internal link equity and preventing orphan pages.
  const related = blogPosts
    .filter((p) => p.slug !== post.slug && (hasContent(p.slug) || p.slug === "seo-fundamentals"))
    .map((p) => ({ p, shared: p.tags.filter((t) => post.tags.includes(t)).length }))
    .sort((a, b) => b.shared - a.shared || +new Date(b.p.date) - +new Date(a.p.date))
    .slice(0, 3)
    .map((x) => x.p);

  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    "@id": `https://sufyan-frontend.vercel.app/blog/${post.slug}`,
    headline: post.title,
    description: post.excerpt,
    datePublished: post.date,
    inLanguage: "en-PK",
    url: `https://sufyan-frontend.vercel.app/blog/${post.slug}`,
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": `https://sufyan-frontend.vercel.app/blog/${post.slug}`,
    },
    image: {
      "@type": "ImageObject",
      url: "https://sufyan-frontend.vercel.app/profile.png",
      width: 1200,
      height: 630,
    },
    author: {
      "@type": "Person",
      "@id": "https://sufyan-frontend.vercel.app/#person",
      name: "Muhammad Sufyan",
      url: "https://sufyan-frontend.vercel.app",
      sameAs: ["https://github.com/sufyan-frontend", "https://www.linkedin.com/in/sufyan-frontend"],
    },
    publisher: {
      "@type": "Organization",
      name: "Muhammad Sufyan — Frontend Developer",
      url: "https://sufyan-frontend.vercel.app",
      logo: {
        "@type": "ImageObject",
        url: "https://sufyan-frontend.vercel.app/favicon.png",
        width: 192,
        height: 192,
      },
    },
    isPartOf: {
      "@type": "Blog",
      "@id": "https://sufyan-frontend.vercel.app/blog",
      name: "Muhammad Sufyan — Frontend Development Blog",
      url: "https://sufyan-frontend.vercel.app/blog",
    },
    keywords: post.tags.join(", "),
  };

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://sufyan-frontend.vercel.app/" },
      { "@type": "ListItem", position: 2, name: "Blog", item: "https://sufyan-frontend.vercel.app/blog" },
      { "@type": "ListItem", position: 3, name: post.title, item: `https://sufyan-frontend.vercel.app/blog/${post.slug}` },
    ],
  };

  return (
    <div className="pt-24 pb-20">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <div className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link
          href="/blog"
          className="inline-flex items-center gap-2 text-surface/60 hover:text-primary text-sm mb-10 transition-colors"
        >
          <svg className="w-4 h-4 rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
          </svg>
          Back to Blog
        </Link>

        <div className="flex flex-wrap gap-2 mb-4">
          {post.tags.map((tag) => (
            <span key={tag} className="text-xs bg-primary/10 text-primary px-2 py-1 rounded-full">
              {tag}
            </span>
          ))}
        </div>

        <h1 className="text-3xl sm:text-4xl font-bold text-surface mb-4">{post.title}</h1>

        <div className="flex items-center gap-4 text-surface/50 text-sm mb-10 pb-8 border-b border-white/5">
          <time dateTime={post.date}>
            {new Date(post.date).toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          </time>
          <span aria-hidden="true">·</span>
          <span>{post.readTime} read</span>
        </div>

        <p className="text-surface/70 text-lg leading-relaxed mb-8">{post.excerpt}</p>

        {blogContent[post.slug] && (
          <div className="prose-custom">{blogContent[post.slug]}</div>
        )}

        {related.length > 0 && (
          <aside className="mt-16 pt-10 border-t border-white/5">
            <h2 className="text-surface font-semibold text-lg mb-6">Related Articles</h2>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {related.map((r) => (
                <Link
                  key={r.slug}
                  href={`/blog/${r.slug}`}
                  className="group block rounded-2xl border border-white/5 bg-white/2 p-5 hover:border-primary/30 hover:bg-white/4 transition-colors"
                >
                  <div className="flex flex-wrap gap-1.5 mb-3">
                    {r.tags.slice(0, 2).map((t) => (
                      <span key={t} className="text-[10px] bg-primary/10 text-primary px-2 py-0.5 rounded-full">
                        {t}
                      </span>
                    ))}
                  </div>
                  <h3 className="text-surface text-sm font-semibold leading-snug mb-2 group-hover:text-primary transition-colors line-clamp-2">
                    {r.title}
                  </h3>
                  <p className="text-surface/50 text-xs leading-relaxed line-clamp-2">{r.excerpt}</p>
                  <span className="mt-3 inline-flex items-center gap-1 text-primary text-xs font-medium">
                    Read more
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                    </svg>
                  </span>
                </Link>
              ))}
            </div>
          </aside>
        )}
      </div>
    </div>
  );
}
